services:
  - type: web
    name: nutriscan-api
    env: node
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: API_KEYS
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: "*"
